### ISSUE TITLE
Historical data

### ISSUE THREAD

**Issue by franz101** [pratporetw/trool#1]
Did you manage to get useful historical data?

**Comment by pratporetw** [comment]
Can you specify what kind of data you are looking for? If you are interested in historical option chain data, than you can get day end option chain data only. Here is one of the links: https://www.fnoanalysis.com/oi/option_chain_hist.php

**Comment by kumarraditya** [comment]
Will option chain be used without selenium, only use of python ? Just downlaoding data from nse or external feeder  then can your tool is used for parsing ?

**Comment by pratporetw** [comment]
No. It can't be used only for parsing. I am storing data in a certain format which is being read in the Jupyter notebook.
