### ISSUE TITLE
National Stock Exchange- Unauthorized Tool Removal Request https://github.com/pratporetw/trool

### ISSUE THREAD

**Issue by Cybersecurity-Specialist** [pratporetw/trool#2]
Hi,

This is Rogelio from IZOOlogic,a private security company authorized to represent National Stock Exchange.

It has come to our attention that a new tool(s) were created to extract information to nseindia.com website for the purpose of stock market trend movement and other intent the developer may have in mind. We are explicitly directed to by our client omission of the script found on github repository.

Script whereabout : https://github.com/pratporetw/trool

Here is our contact details in case  you would like to discuss this.

Level 30, The Leadenhall Building,
122 Leadenhall Street, EC3V 4AB
City of London, UNITED KINGDOM
+44 20 3734 2726
izoolabs@izoologic.com

We would appreciate your full compliance.

Best Regards,
Rogelio Deloso

**Comment by pratporetw** [comment]
Have removed the references to nseindia. Thanks.
